Update event_triggers.yml

diff --git a/.github/workflows/event_triggers.yml b/.github/workflows/event_triggers.yml
--- a/.github/workflows/event_triggers.yml
+++ b/.github/workflows/event_triggers.yml
@@ -13,20 +13,22 @@ jobs:
         run: |
           echo "Running job"
           # Simulate a successful or failing command
-          # For example, to simulate failure, use `exit 1` instead of `echo`
-          exit 0   # Change to `exit 1` to simulate failure
+          # Use `exit 1` to simulate failure
+          exit 0
 
       - name: Send Slack Notification
-        if: always()  # Ensure this step runs even if the job fails
+        if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
           if [ "${{ job.status }}" == "success" ]; then
             curl -X POST -H 'Content-type: application/json' \
-            --data '{"text":"Job is successful! 🎉"}' \
-            $SLACK_WEBHOOK_URL
+              --data '{"text":"✅ Job is successful! 🎉"}' \
+              $SLACK_WEBHOOK_URL
           else
             curl -X POST -H 'Content-type: application/json' \
-            --data '{"text":"Job failed with an error message! ❌"}' \
-            $SLACK_WEBHOOK_URL
-          fi
+              --data '{"text":"❌ Job failed with an error message!"}' \
+              $SLACK_WEBHOOK_URL
+
+      - name: Print Final Message
+        run: echo "hello this is my first pipeline"
